Title argument
wezterm/wezterm pull request #4130
Opened 2023-08-10 21:46 UTC by diniamo

I probably missed a few things, and I'm not sure about a few others, please point out or ask anything that should be changed.

Closes #4118

2023-10-12 16:17 UTC, rare-magma commented
it would be great to have this feature in wezterm! @wez

2024-02-23 14:09 UTC, ricardoseriani commented
This feature will be very helpful, so I can have a fixed title in every terminal, making easy to search using rofi or any other solution.

2024-09-20 17:57 UTC, Zeioth commented
I'd like to bring attention to this PR. Because not having this is a deal breaker.

2024-09-21 14:44 UTC, port19x commented
I'm setting a 10 USD bounty on the merge of this PR.
Paid via github sponsorship

2024-11-20 18:42 UTC, th3r00t commented
Any update  on this?

2025-08-04 09:04 UTC, axelkar commented
C'mon @wez it's been two years... No review even?

2025-08-04 11:45 UTC, axelkar requested changes

2025-08-04 11:45 UTC, axelkar commented on wezterm-gui/src/termwindow/mod.rs
> +    static ref WINDOW_TITLE: Mutex<Option<String>> = Mutex::new(None);
Implementing `--title` this way irreversibly (Lua can't control it anymore) overrides the window title for all windows. With single-instance being the default this is worsened even more.

2025-08-04 11:50 UTC, diniamo commented on wezterm-gui/src/termwindow/mod.rs
> +    static ref WINDOW_TITLE: Mutex<Option<String>> = Mutex::new(None);
I would have done small nits, but I'm not going to do anything more, when I don't use Wezterm. You are free to use my code (if it helps at all), and/or open a new PR for this feature.

2025-08-05 05:44 UTC, wez commented
FWIW, I did take a peek at this when it first popped up, and didn't agree with the implementation approach.  I had planned to come back to this to comment to that effect, but I've had a lot happening in my life and it got away from me.

Since the OP is no longer using wezterm, let's close this one.

If someone wants to pick up the idea of setting an initial title, the implementation needs to set the title just for the first pane created by that wezterm invocation.

There are additional questions that should be asked, and answered, about how that might interact with an invocation that re-uses an existing gui session; I think there would need to be some additional work in the mux protocol to facilitate spawning with an initial title, which would then imply that spawning in general should have the option to set the title, and then there should also be fan out to all API surfaces that spawn to expose that argument.

There's a lot more to a fully implemented version of this PR that there appears.

2025-08-05 05:44 UTC, closed without merging