Update pane index when moving panes in same tab
wezterm/wezterm pull request #6029
Opened 2024-08-25 00:21 UTC by scauligi

Fixes #6028.
Not sure if this is the best solution, but it works.

2024-09-14 18:16 UTC, wez requested changes
Thanks for this!

I have a suggestion that I think makes the flow clearer overall, and which will be more robust against other changes that might mutate the tab contents in the future

2024-09-14 18:16 UTC, wez commented on mux/src/domain.rs
> +
Let's make this unconditional but move it to just before the `tab.split_and_insert` call on line 142:

```suggestion
                   // May need to update pane_index if the logic above mutated the tab contents
                   let pane_index = match tab
                        .iter_panes_ignoring_zoom()
                        .iter()
                        .find(|p| p.pane.pane_id() == pane_id)
                    {
                        Some(p) => p.index,
                        None => anyhow::bail!("invalid pane id {}", pane_id),
                    };
```

2024-09-14 18:16 UTC, wez commented on mux/src/domain.rs
> +        let mut pane_index = match tab
with the changes suggested below, we can keep this immutable, which makes the code overall easier to reason about:

```suggestion
        let pane_index = match tab
```

2024-09-18 03:14 UTC, scauligi commented
I think this change is in line with what you're suggesting? There's a minor complication in that the pre-removal `pane_index` is needed to calculate `split_size`, but the post-removal `pane_index` is what we need for the final `tab.split_and_insert` call.

2024-09-22 17:51 UTC, wez commented
Yeah, this is what I was thinking. The complication you mentioned just sounds like how this works now, or did you mean that phrasing the code this way introduces another issue?

2024-10-06 21:24 UTC, scauligi commented
Whoops! Lost track of this and forgot to reply.
The "complication" was in reference to the fact that the new pane index is needed for the `tab.split_and_insert` call, so recalculating it inside the nested scope wouldn't work since we need the new index in the outer scope (which my latest change should be taking care of).

2025-02-09 20:31 UTC, merged

2025-02-09 20:33 UTC, wez commented
Thank you!