add cellwidths option #6289
wezterm/wezterm pull request #6290
Opened 2024-10-17 05:17 UTC by hamano

2025-02-08 22:24 UTC, wez requested changes
Thanks for this!
It makes sense to me, and the approach seems reasonable and easy to follow.
I have a couple of stylistic suggestions, but the main point of feedback is that we need to adjust this a bit to avoid excessive copying of the map in the hot code paths.

2025-02-08 22:24 UTC, wez commented on term/src/terminalstate/performer.rs
> +            let print_width = grapheme_column_width(g, Some(self.unicode_version.clone()));
re: performance anxiety, this is a very hot loop, especially for folks doing `cat bigfile`.

I think we should be passing `Some(&self.unicode_version)` here to avoid any additional overhead.

There will be more API fan-out, but I think it is worth it to keep the performance reasonable.

The termwiz Cargo.toml version number would also need to be bumped because it would be a breaking API change, even though it is a minor one.

2025-02-08 22:24 UTC, wez commented on termwiz/src/cell.rs
> +}
From a layering perspective, I think this struct should move to the `config` crate, and that the `setcellwidths` function should move along with it.  I would probably also move `setcellwidths` to be an associated function of `CellWidth`

```rust
impl CellWidth {
   fn compile_to_map(widths: Option<Vec<Self>>) -> Option<Arc<HashMap<u32,u8>>> {
     ...
   }
}
```

2025-02-08 22:24 UTC, wez commented on termwiz/src/cell.rs
> +    }
FWIW, you can simply this, something like:

```suggestion
    let cellwidths = cellwidths.as_ref()?;
    let mut map = HashMap::new();
    for cellwidth in cellwidths {
        for i in cellwidth.first..=cellwidth.last {
            map.insert(i, cellwidth.width);
        }
    }
    Some(map)
```

2025-02-08 22:24 UTC, wez commented on wezterm-gui/src/main.rs
> +        cellwidths: setcellwidths(config.cellwidths.clone()),
I think it's worth adding a helper method to the `Config` class that encapsulates this:

in `config/src/config.rs`:

```rust
impl Config {
   pub fn unicode_verson(&self) -> UnicodeVersion {
      ...
   }
}
```

then the logic in this file is simply:

```rust
let unicode_version = config.unicode_version();
```

2025-02-08 22:24 UTC, wez commented on config/src/terminal.rs
> +            cellwidths: setcellwidths(config.cellwidths.clone()),
per my comment in `main.rs`, I think this method could simplify down to:

```rust
 fn unicode_version(&self) -> UnicodeVersion {
      let config = self.configuration();
      config.unicode_version()
}
```

2025-02-08 22:24 UTC, wez commented on termwiz/src/surface/line/line.rs
> +            let cell = Cell::new_grapheme(sub, attrs.clone(), unicode_version.clone());
This is also a hot code path, should probably pass `&unicode_version` here as well

2025-02-08 22:24 UTC, wez commented on termwiz/src/cell.rs
> +        .map(|g| grapheme_column_width(g, version.clone()))
let's pass the version by reference here too

2025-02-14 10:58 UTC, hamano commented on wezterm-gui/src/main.rs
> +        cellwidths: setcellwidths(config.cellwidths.clone()),
added unicode_version() in struct ConfigHandle

2025-02-14 11:05 UTC, hamano commented
Thank you for reviewing.
I have fixed the issues you pointed out and rebased them into a single commit.

2025-03-08 11:11 UTC, wez commented
Hi! There are some issues with the tests, could you fix those and re-submit?

2025-03-08 19:56 UTC, wez reviewed
What we need now is a page for the docs; please see https://github.com/wezterm/wezterm/blob/main/CONTRIBUTING.md#contributing-documentation for information on how to run the doc build.

For this PR, you should add a file alongside `docs/config/lua/config/treat_east_asian_ambiguous_width_as_wide.md` for the new option: `docs/config/lua/config/cell_widths.md`.

For the `since()` version part, use the string `nightly` as the version.

Please include an example of using the new option in that page.

Thanks!

2025-03-08 19:56 UTC, wez commented on config/src/config.rs
> +    pub cellwidths: Option<Vec<CellWidth>>,
Let's use an underscore here to separate the two words

```suggestion
    pub cell_widths: Option<Vec<CellWidth>>,
```

2025-03-08 19:56 UTC, wez commented on termwiz/src/cell.rs
> +    let version = version.as_ref().unwrap_or(&&LATEST_UNICODE_VERSION);
```suggestion
    let version = version.as_deref().unwrap_or(&LATEST_UNICODE_VERSION);
```

2025-03-09 03:57 UTC, ProfessorMOB commented
This might sound like a insane idea, but what if we exposed the harfbuzz API directly through lua in some way?

If we exposed the harfbuzz API directly through Lua, then we could give the user an absurd amount of control over what their characters should look like. I don't think I'll be able to flesh this idea any further do to my own lack of expertise, but I did want to throw it out there. 

Nonetheless, I'm onboard with hamano's approach.

2025-03-10 06:31 UTC, hamano commented
@wez Could you please review the doc 0b3d1e1

2025-03-10 13:02 UTC, wez approved these changes

2025-03-20 04:39 UTC, hamano commented
rebased

2025-03-21 01:20 UTC, hamano commented
@wez  Every time you edit Cargo.lock, a conflict occurs. Should I remove the Cargo.lock changes from the PR?

2025-05-03 13:56 UTC, merged

2025-05-14 20:13 UTC, ProfessorMOB commented
The option works now, but characters like ﷽ still aren't displayed properly, its now taking two spaces instead of one. 

Another problem I ran into was that it was VERY buggy. Here's a video of what I mean. 

https://github.com/user-attachments/assets/de433efc-849c-46b4-a9fc-5ce608ad3a2a

2025-05-14 21:37 UTC, wez commented
if your shell, or other application that you are using, doesn't agree with the terminal on the width, then this is exactly the sort of behavior that you can expect. This is mentioned in the documentation.
https://wezterm.org/config/lua/config/cell_widths.html

2025-05-15 00:26 UTC, ProfessorMOB commented
I pointed out two problems in a way that was very unclear, and I apologize. You explained the one of the problems I ran into (where its bugging out and I can't move beyond the character), but there's another problem I'm facing. I had set the cell width to be 5 cells, but it's only displaying the character in the space of 2 cells. Is that also because of the same problem (cellwidths of shell and terminal don't agree)?

And also, how would one force the shell to agree with the cellwidth specified? I read the docs its because of the glibc locale, would I have to change the locale for me to fix that?

2025-05-15 01:07 UTC, hamano commented
The cell_widths option is intended only for widths of 1 or 2.
Even if support for widths of 3 or more were supported, it wouldn't be useful since both Vim and the glibc locale only handle widths of 1 or 2. Supporting terminals alone would not be practical.

For customizing the locale, we use this repository.
https://github.com/hamano/locale-eaw
Apologies that the README is in Japanese.
Add the following to config.ini:
```
[CUSTOM]
U+FDFD = 2
```

Then run `./gen.py`, and `UTF-8-CUSTOM.gz` will be generated.
Linux users can use this to customize character widths in Bash and Zsh.

2025-05-15 01:14 UTC, hamano commented
As for macOS, I’ve heard that modifying the locale is difficult due to security protections.
I’d like to know more as well, so please let me know if you find a way to do it.

2025-05-15 01:33 UTC, ProfessorMOB commented
Personally, no need to apologize to me about the Readme being in Japanese, I just wish technology wasn't so anglicised. 

As for MacOS, I found this (https://apple.stackexchange.com/questions/384388/how-to-add-a-new-locale-to-macos-catalina) from stackoverflow, I don't have experience with Linux locale or locale in general. I found this with a quick google search. Dunno if it applies to later versions of MacOS though.